### ISSUE TITLE
<system|char|{> breaks token

### ISSUE THREAD

**Issue by s1m0nj** [rappen/Rappen.XTB.Helper#20]
We love this solution, we have templates we are using to generate some basic JSON messages, however when we use a system char of { it breaks the rest of the token system.

`<system|char|{>
"status_code": "{statuscode}",
 <system|char|}>`

Results in

`{
"status_code": "{statuscode}",
<system|char|}>`

Removing the first line and all is good.

Any ideas on a fix for this?

**Comment by rappen** [comment]
Related to #6

**Comment by s1m0nj** [comment]
Thanks for coming back to me so quickly, we just using the library.

**Comment by s1m0nj** [comment]
We've done a hack to work around it.  We know it's not a good solution, but it will work for our situation.  Assume it might not wont work in <iff| statements etc
![image](https://user-images.githubusercontent.com/1045043/189148577-3bbe343b-6310-4b9a-ab6c-965bcf4667c0.png)

**Comment by s1m0nj** [comment]
We've done a hack to work around it in our copy of the source but dont think it's good enough to submit a pull request.  It will work for our requirements 

![image](https://user-images.githubusercontent.com/1045043/189148577-3bbe343b-6310-4b9a-ab6c-965bcf4667c0.png)

**Comment by s1m0nj** [comment]
We've done a hack to work around it in our copy of the source but dont think it's good enough to submit a pull request.  It will work for our requirements 

![image](https://user-images.githubusercontent.com/1045043/189148577-3bbe343b-6310-4b9a-ab6c-965bcf4667c0.png)

**Comment by rappen** [comment]
Thanks! Good idea, but I agree with what you say, so this is "a good start" for my fixing this problem.

**Comment by rappen** [comment]
Fixed this problem.
I worked a while about this issue - and basically your idea was the best solution.
Closing for now - reopen if this is not good enough!

**Comment by rappen** [comment]
Docs: https://jonasr.app/xrm-tokens/#system

**Comment by s1m0nj** [comment]
Awsome, thank you!
