### ISSUE TITLE
Request: {accountid|<dynamicurl>}

### ISSUE THREAD

**Issue by s1m0nj** [rappen/Rappen.XTB.Helper#21]
Just throw this out there, it would be great if we could get a dynamic url for any entity reference to keep things tidy.

input
`{accountid|<dynamicurl>}`
output
`https://example.crm4.dynamics.com/main.aspx?pagetype=entityrecord&etn=accountid&id=12345678-1234-1234-1234-123456789012`

I see you have a Util for DeepLink but I'm not sure if it's possible to get the webappurl from the sdk or ClientService object?  Assuming we're unable to call out to the Global Discovery Service to get it, I guess a simple solution could be set in the library by the calling code?

Love this library, thanks for sharing it.

**Comment by rappen** [comment]
Interesting...!
I'll see what we can do.

**Comment by s1m0nj** [comment]
Thanks Jonas.  I guess it should be  {accountid|<recordurl>} to match the entity property in the old workflow editor.

**Comment by rappen** [comment]
I'm having a hard time with this request...
The end part of the URL is no problem:
`?pagetype=entityrecord&etn=rapp_rocket&id=5a52b5bd-6f7b-ec11-8d21-6045bd8a4289`
But the first in the URL is impossible (from my knowledge):
`https://xyz.crm4.dynamics.com/main.aspx`

In this case, we only have the `IOrganizationService` that has zero publics about where you are connected to.

Would it be any use with only the parameters in the URL, without the host part?
Any other ideas?

**Comment by s1m0nj** [comment]
Hi Jonas,

It seems we can get it from RetrieveCurrentOrganizationRequest (released in 2015 apparently - news to me).  Just tested it and it's what we need.

```
var request = new RetrieveCurrentOrganizationRequest();
var response = (RetrieveCurrentOrganizationResponse)service.Execute(request);
var uriString = response.Detail.Endpoints[EndpointType.WebApplication];
```

uriString will return 
`https://xyz.crm4.dynamics.com/`

Thanks 
Si

**Comment by s1m0nj** [comment]
Just for FYI Github copilot wrote some code for OrganizationDetail.Endpoints.  (Copilot amazes me everyday, well worth the cost and has improved my code no end!)

So I tested that aswell, if you are using the .net core ServiceClient for the Dataverse then the web application server origin can be found here.  

```
Microsoft.PowerPlatform.Dataverse.Client.ServiceClient service =  new ServiceClient(Settings.DataverseConnectionString);
var uriString = service.OrganizationDetail.Endpoints[Microsoft.Xrm.Sdk.Discovery.EndpointType.WebApplication];
```

uriString will return
`https://xyz.crm4.dynamics.com/`

**Comment by s1m0nj** [comment]
Just for FYI if you're using the Dataverse ServiceClient then it can be found here.

 var uriString = service.OrganizationDetail.Endpoints.FirstOrDefault(ep => (int)ep.Key == (int)EndpointType.WebApplication).Value;

**Comment by rappen** [comment]
This is my tests, using markdown:
```
[{fullname}]({contactid|<recordurl>})
[{parentcustomerid}]({parentcustomerid|<recordurl>})
[{parentcustomerid.modifiedby}]({parentcustomerid.modifiedby|<recordurl>})
[{parentcustomerid.modifiedby.businessunitid}]({parentcustomerid.modifiedby.businessunitid|<recordurl>})
[{parentcustomerid.modifiedby.businessunitid.organizationid}]({parentcustomerid.modifiedby.businessunitid.organizationid|<recordurl>})
Plain link: {parentcustomerid.modifiedby|<recordurl>}
```
This is my results:

> [Elon Musk](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=contact&id=b423dbf9-d147-ec11-8c62-6045bd870ceb)
> [SpaceX](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=account&id=c423dbf9-d147-ec11-8c62-6045bd870ceb)
> [Jonas Rapp](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=systemuser&id=b5863a5c-5934-ec11-8c65-000d3a217588)
> [orgd2bb5717](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=businessunit&id=c37f3a5c-5934-ec11-8c65-000d3a217588)
> [orgd2bb5717](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=organization&id=738dbdf7-a684-47cc-9bf8-0a135d3ba368)
> Plain link: https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=systemuser&id=b5863a5c-5934-ec11-8c65-000d3a217588

Ok, the links don't really work, since I faked the server only in this case.

Good enough?

**Comment by rappen** [comment]
Another example:
```
Company: [{name}]({accountid|<recordurl>})
Boss: [{primarycontactid}]({primarycontactid|<recordurl>})
Workers:
  <expand|contact|parentcustomerid|[{fullname}]({contactid|<recordurl>})|fullname|
  |true|true|>
```
Result:

> Company: [Oil Drilling Company](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=account&id=4ccf03b8-87a3-ec11-983f-000d3a4be01e)
> Boss: [Harry S. Stamper](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=contact&id=cb479557-7141-ec11-8c62-6045bd8d92e1)
> Workers:
>   [A.J. Frost](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=contact&id=87a1ae69-7141-ec11-8c62-6045bd8d92e1)
>   [Bear](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=contact&id=2f2e86e1-9441-ec11-8c62-6045bd8d92e1)
>   [Harry S. Stamper](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=contact&id=cb479557-7141-ec11-8c62-6045bd8d92e1)
>   [Jo Rock](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=contact&id=2355b467-533e-ec11-8c63-000d3a4a08d0)
>   [Oscar](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=contact&id=d33fa1da-9441-ec11-8c62-6045bd8d92e1)
>   [Rockhound x](https://xyz.crm4.dynamics.com//main.aspx?pagetype=entityrecord&etn=contact&id=16cfc06e-9441-ec11-8c62-6045bd8d92e1)

**Comment by rappen** [comment]
Docs: https://jonasr.app/xrm-tokens/#recordurl
