### ISSUE TITLE
Lookup Dialog : Define default view if none exists for an entity

### ISSUE THREAD

**Issue by MscrmTools** [rappen/Rappen.XTB.Helper#4]
So I used this open source project for my latest tool but I am facing a limitation in the lookup dialog

Some entities don't have any system view (like appmodule entity) and I would like this Lookup Dialog to generate a fake view if none are available.

The view would be as simple as display all records with only the primary name column

**Comment by MscrmTools** [comment]
Entity appmodule for example does not have any view

**Comment by rappen** [comment]
Just checking - this is done with #5, right?

**Comment by MscrmTools** [comment]
I would say yes
