### ISSUE TITLE
Calculated Values with Curly Brackets {}

### ISSUE THREAD

**Issue by corehop** [rappen/Rappen.XTB.Helper#6]
To recreate:
-Save "Things inside curly brackets are {not} removed" in any text field of any record type.
-Use BulkDataUpdater to set the value to a calculated value of the field (ex: set description to {description})
-Notice that the value inside the curly brackets is now gone

Here is a screenshot showing in the Calculate preview that {not} has been removed:
![image](https://user-images.githubusercontent.com/9593801/116609601-29b5c200-a8fa-11eb-9747-afce816c4a3b.png)

**Comment by rappen** [comment]
Now the XRM Token will never run an iteration in the replacements in the results values.

Not yet been published in either Bulk Data Updater or XRM Tokens Runner. Stay tuned.
